name: Deploy
on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build and Publish API
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish backend/LaborControl.API/LaborControl.API.csproj -c Release -o ./publish/api

      - name: Deploy API to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: laborcontrol-dmtt-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish/api

      - name: Build and Publish Dashboard
        run: dotnet publish web-dashboard/LaborControl.Dashboard/LaborControl.Dashboard.csproj -c Release -o ./publish/dashboard

      - name: Deploy Dashboard to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: laborcontrol-dmtt-dashboard
          publish-profile: ${{ secrets.AZURE_DASHBOARD_PUBLISH_PROFILE }}
          package: ./publish/dashboard
