name: Test Azure Action
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          mkdir -p testpkg
          echo "Hello from GitHub Actions" > testpkg/test.txt

      - name: Deploy to Azure (API)
        uses: azure/webapps-deploy@v2
        with:
          app-name: laborcontrol-dmtt-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: testpkg
